import { Card } from '@/lib/types';
import { FabricSwatch } from '@/lib/types/card';

// Sample cards for development and testing
export const sampleCards: Card[] = [
  {
    id: 'sample-1',
    title: 'Gundam RX-78-2',
    name: 'Gundam RX-78-2',
    description: 'Classic Gundam mecha featured in the original Mobile Suit Gundam anime series.',
    imageUrl: '/sample-images/gundam.jpg',
    image: '/sample-images/gundam.jpg',
    thumbnailUrl: '/sample-images/gundam-thumb.jpg',
    userId: 'demo-user',
    creatorId: 'demo-user',
    tags: ['anime', 'mecha', 'gundam', 'collectible'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    fabricSwatches: [],
    effects: ['Holographic'], // Add required effects property
  },
  {
    id: 'sample-2',
    title: 'Lakers Kobe Bryant',
    name: 'Lakers Kobe Bryant',
    description: 'Limited edition Kobe Bryant collectible card featuring the Lakers legend.',
    imageUrl: '/sample-images/kobe.jpg',
    image: '/sample-images/kobe.jpg',
    thumbnailUrl: '/sample-images/kobe-thumb.jpg',
    userId: 'demo-user',
    creatorId: 'demo-user',
    tags: ['basketball', 'lakers', 'kobe', 'nba'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    fabricSwatches: [],
    effects: ['Refractor', 'Chrome'], // Add required effects property
  },
  {
    id: 'sample-3',
    title: 'Football Running Back',
    name: 'Football Running Back',
    description: 'Dynamic action shot of an NFL running back breaking through defenses.',
    imageUrl: '/sample-images/football.jpg',
    image: '/sample-images/football.jpg',
    thumbnailUrl: '/sample-images/football-thumb.jpg',
    userId: 'demo-user',
    creatorId: 'demo-user',
    tags: ['football', 'nfl', 'sports', 'running-back'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    fabricSwatches: [],
    effects: ['Vintage'], // Add required effects property
  },
  {
    id: 'sample-4',
    title: 'Golden Gate Quarterback',
    name: 'Golden Gate Quarterback',
    description: 'Iconic San Francisco quarterback with the Golden Gate bridge backdrop.',
    imageUrl: '/sample-images/quarterback.jpg',
    image: '/sample-images/quarterback.jpg',
    thumbnailUrl: '/sample-images/quarterback-thumb.jpg',
    userId: 'demo-user',
    creatorId: 'demo-user',
    tags: ['football', '49ers', 'san-francisco', 'vintage'],
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    fabricSwatches: [],
    effects: ['Chrome'], // Add required effects property
  },
  {
    id: 'sample-5',
    title: 'Garbage Pail Kids - Bob Ooze',
    name: 'Garbage Pail Kids - Bob Ooze',
    description: 'Vintage 80s Garbage Pail Kids collectible card featuring classic gross-out humor.',
    imageUrl: '/sample-images/garbage-pail-kids.jpg',
    image: '/sample-images/garbage-pail-kids.jpg',
    thumbnailUrl: '/sample-images/garbage-pail-kids-thumb.jpg',
    userId: 'demo-user',
    creatorId: 'demo-user',
    tags: ['vintage', '80s', 'garbage-pail-kids', 'collectible'],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    fabricSwatches: [],
    effects: ['Vintage', 'Holographic'], // Add required effects property
  },
  {
    id: 'sample-6',
    title: 'LeBron James - Lakers Legend',
    name: 'LeBron James - Lakers Legend',
    description: 'Special edition Lakers LeBron James card with artistic surreal background.',
    imageUrl: '/sample-images/lebron.jpg',
    image: '/sample-images/lebron.jpg',
    thumbnailUrl: '/sample-images/lebron-thumb.jpg',
    userId: 'demo-user',
    creatorId: 'demo-user',
    tags: ['basketball', 'lakers', 'lebron', 'nba'],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    fabricSwatches: [],
    effects: ['Refractor'], // Add required effects property
  }
];
