
import { Card } from './types';
import { v4 as uuidv4 } from 'uuid';

export const sampleCards = [
  {
    id: 'card-001',
    title: 'Vintage Baseball Card',
    description: 'A classic baseball card from the golden era',
    imageUrl: '/lovable-uploads/a38aa501-ea2d-4416-9699-1e69b1826233.png',
    thumbnailUrl: '/lovable-uploads/a38aa501-ea2d-4416-9699-1e69b1826233.png',
    tags: ['baseball', 'vintage', 'collectible'],
    userId: 'user1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    effects: [],
    designMetadata: {
      player: 'Honus Wagner',
      team: 'Pittsburgh Pirates',
      year: '1909-11'
    }
  },
  {
    id: 'card-002',
    title: 'Mickey Mantle Card',
    description: 'Iconic 1952 Topps Mickey Mantle rookie card',
    imageUrl: '/lovable-uploads/667e6ad2-af96-40ac-bd16-a69778e14b21.png',
    thumbnailUrl: '/lovable-uploads/667e6ad2-af96-40ac-bd16-a69778e14b21.png',
    tags: ['baseball', 'rookie', 'valuable'],
    userId: 'user1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    effects: [],
    designMetadata: {
      player: 'Mickey Mantle',
      team: 'New York Yankees',
      year: '1952'
    }
  },
  {
    id: 'card-003',
    title: 'Babe Ruth Card',
    description: 'Historic Babe Ruth baseball card',
    imageUrl: '/lovable-uploads/79a099b9-c77a-491e-9755-ba25419791f5.png',
    thumbnailUrl: '/lovable-uploads/79a099b9-c77a-491e-9755-ba25419791f5.png',
    tags: ['baseball', 'legend', 'collectible'],
    userId: 'user1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    effects: [],
    designMetadata: {
      player: 'Babe Ruth',
      team: 'New York Yankees',
      year: '1933'
    }
  },
  {
    id: 'card-004',
    title: 'Oakland A\'s Memory Card',
    description: 'Custom card from Oakland Athletics game',
    imageUrl: '/lovable-uploads/c23d9e1a-4645-4f50-a9e4-2a325e3b4a4d.png',
    thumbnailUrl: '/lovable-uploads/c23d9e1a-4645-4f50-a9e4-2a325e3b4a4d.png',
    tags: ['baseball', 'oakland', 'memory'],
    userId: 'user1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    effects: [],
    designMetadata: {
      team: 'Oakland Athletics',
      year: '2023'
    }
  }
];

export const addSampleCards = async (
  addCardFunction: (card: Omit<Card, 'id' | 'createdAt' | 'updatedAt'>) => Card
): Promise<Card[]> => {
  const addedCards: Card[] = [];
  
  try {
    for (const sampleCard of sampleCards) {
      // Remove the properties that should be generated by the addCard function
      const { id, createdAt, updatedAt, ...cardData } = sampleCard;
      
      // Add the card
      const newCard = addCardFunction({
        ...cardData,
        id: uuidv4() // Generate a new UUID for this card to avoid conflicts
      });
      
      addedCards.push(newCard);
    }
    
    return addedCards;
  } catch (error) {
    console.error('Error adding sample cards:', error);
    throw error;
  }
};
